version: '3.8'

networks:
  default-network:
    driver: bridge

services:

  user-service:
    container_name: user-service
    depends_on:
      user-service-storage:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
    environment:
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=6060
      - LOG_LVL=info
      - STORAGE_HOST=user-service-storage
      - STORAGE_PORT=5432
      - STORAGE_USER=postgres
      - STORAGE_PASSWORD=postgres
      - USER_DB_NAME=postgres
      - USER_TABLE_NAME=users
      - CITY_TABLE_NAME=city
      - INTEREST_TABLE_NAME=interest
      - USER_PER_INTEREST_TABLE_NAME=user_per_interest
    ports:
      - "6060:6060"
    networks:
      - default-network

  user-service-storage:
    image: postgres:latest
    container_name: user-service-storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker-volumes/storage-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - default-network